### ISSUE TITLE
여행 상품 정보 List 표시

### ISSUE THREAD

**Issue by seongbin9786** [seongbin9786/wanted-pre-onboarding-frontend-a2#1]
## 목적 
- 여행 상품 List를 가져와 표시

## Tasks
- [x] [5m] json 가져오기
- [x] [20m] Suspense로 로딩 상태 처리
  - 실제로 1시간 20분 소요 (...)
- [x] [20m] chakra-ui의 Skeleton 사용
- [x] 예약하기 버튼 토클
- [ ] 자세히 보기 토글
  - Modal 구성
